# Generated by Django 2.2.17 on 2023-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_updater_stima', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='firmware',
            constraint=models.UniqueConstraint(fields=('firmware', 'version', 'revision'), name='unique_firmware'),
        ),
    ]
