#!/usr/bin/python
# GPL. (C) 2014 Paolo Patruno.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'rmap.settings'
import django
django.setup()

import logging,logging.handlers
from rmap import daemon
import pika, subprocess
import threading,Queue
import rmap.settings
import time

user=rmap.settings.amqpuser
password=rmap.settings.amqppassword
host="localhost"
queue="mqtt"


amqp2mqttd = daemon.Daemon(
        stdin="/dev/null",
        stdout=rmap.settings.logfileamqp2mqttd,
        stderr=rmap.settings.errfileamqp2mqttd,
        pidfile=rmap.settings.lockfileamqp2mqttd,
        user=rmap.settings.useramqp2mqttd,
        group=rmap.settings.groupamqp2mqttd
)

send_queue = Queue.Queue()
receive_queue = Queue.Queue()


class Threaded_bufr2mqtt(threading.Thread):
    def __init__(self,delivery_tag):
        threading.Thread.__init__(self)
        self.delivery_tag=delivery_tag

    def run(self):

        body = send_queue.get()

        try:
            amqp2mqttd.procs = [subprocess.Popen(["bufr2mqtt","-t","report","-u",user,"-P",password], stdin=subprocess.PIPE)]
            amqp2mqttd.procs[0].communicate(input=body)

            r = amqp2mqttd.procs[0].wait()
            if r != 0:
                logger.error("There were some errors executing bufr2mqtt ({})".format(r))
                #logger.info("----\n{}\n---".format(body))
                #self.stop()
                raise bufr2mqtt_error
        except:
            logger.error("There were some errors executing bufr2mqtt")
            #self.stop()
            #raise bufr2mqtt_error
            # raise TODO: enqueue in error
            receive_queue.put_nowait(("nook",self.delivery_tag))

        else:
            
            logger.info("Task done: thread terminated")
            receive_queue.put_nowait(("ok",self.delivery_tag))


class amqpConsumer(object):

    def __init__(self):
        """Create a new instance of the consumer class, passing in the AMQP
        URL used to connect to RabbitMQ.

        :param str amqp_url: The AMQP url to connect with

        """
        self._connection = None
        self._channel = None
        self._closing = False
        self._consumer_tag = None

    def connect(self):
        """This method connects to RabbitMQ, returning the connection handle.
        When the connection is established, the on_connection_open method
        will be invoked by pika.

        :rtype: pika.SelectConnection

        """
        logger.info('Connecting to %s', host)

        credentials=pika.PlainCredentials(user, password)
        return pika.SelectConnection(pika.ConnectionParameters(host=host,credentials=credentials),
                                     self.on_connection_open,
                                     stop_ioloop_on_close=False)


    def on_connection_open(self, unused_connection):
        """This method is called by pika once the connection to RabbitMQ has
        been established. It passes the handle to the connection object in
        case we need it, but in this case, we'll just mark it unused.

        :type unused_connection: pika.SelectConnection

        """
        logger.info('Connection opened')
        self.add_on_connection_close_callback()
        self.open_channel()

    def add_on_connection_close_callback(self):
        """This method adds an on close callback that will be invoked by pika
        when RabbitMQ closes the connection to the publisher unexpectedly.

        """
        logger.info('Adding connection close callback')
        self._connection.add_on_close_callback(self.on_connection_closed)

    def on_connection_closed(self, connection, reply_code, reply_text):
        """This method is invoked by pika when the connection to RabbitMQ is
        closed unexpectedly. Since it is unexpected, we will reconnect to
        RabbitMQ if it disconnects.

        :param pika.connection.Connection connection: The closed connection obj
        :param int reply_code: The server provided reply_code if given
        :param str reply_text: The server provided reply_text if given

        """
        self._channel = None
        if self._closing:
            self._connection.ioloop.stop()
        else:
            logger.warning('Connection closed, reopening in 5 seconds: (%s) %s',
                           reply_code, reply_text)
            self._connection.add_timeout(5, self.reconnect)

    def reconnect(self):
        """Will be invoked by the IOLoop timer if the connection is
        closed. See the on_connection_closed method.

        """
        # This is the old connection IOLoop instance, stop its ioloop
        self._connection.ioloop.stop()

        if not self._closing:
            self.run()

    def open_channel(self):
        """Open a new channel with RabbitMQ by issuing the Channel.Open RPC
        command. When RabbitMQ responds that the channel is open, the
        on_channel_open callback will be invoked by pika.

        """
        logger.info('Creating a new channel')
        self._connection.channel(on_open_callback=self.on_channel_open)

    def on_channel_open(self, channel):
        """This method is invoked by pika when the channel has been opened.
        The channel object is passed in so we can make use of it.

        Since the channel is now open, we'll declare the exchange to use.

        :param pika.channel.Channel channel: The channel object

        """
        logger.info('Channel opened')
        self._channel = channel
        self.add_on_channel_close_callback()

        self.start_consuming()


    def add_on_channel_close_callback(self):
        """This method tells pika to call the on_channel_closed method if
        RabbitMQ unexpectedly closes the channel.

        """
        logger.info('Adding channel close callback')
        self._channel.add_on_close_callback(self.on_channel_closed)

    def on_channel_closed(self, channel, reply_code, reply_text):
        """Invoked by pika when RabbitMQ unexpectedly closes the channel.
        Channels are usually closed if you attempt to do something that
        violates the protocol, such as re-declare an exchange or queue with
        different parameters. In this case, we'll close the connection
        to shutdown the object.

        :param pika.channel.Channel: The closed channel
        :param int reply_code: The numeric reason the channel was closed
        :param str reply_text: The text reason the channel was closed

        """
        logger.warning('Channel %i was closed: (%s) %s',
                       channel, reply_code, reply_text)
        self._connection.close()


    def start_consuming(self):
        """This method sets up the consumer by first calling
        add_on_cancel_callback so that the object is notified if RabbitMQ
        cancels the consumer. It then issues the Basic.Consume RPC command
        which returns the consumer tag that is used to uniquely identify the
        consumer with RabbitMQ. We keep the value to use it when we want to
        cancel consuming. The on_message method is passed in as a callback pika
        will invoke when a message is fully received.

        """
        logger.info('Issuing consumer related RPC commands')
        self.add_on_cancel_callback()
        self._channel.basic_qos(prefetch_count=3)
        self._consumer_tag = self._channel.basic_consume(self.on_message,queue)

    def add_on_cancel_callback(self):
        """Add a callback that will be invoked if RabbitMQ cancels the consumer
        for some reason. If RabbitMQ does cancel the consumer,
        on_consumer_cancelled will be invoked by pika.

        """
        logger.info('Adding consumer cancellation callback')
        self._channel.add_on_cancel_callback(self.on_consumer_cancelled)

    def on_consumer_cancelled(self, method_frame):
        """Invoked by pika when RabbitMQ sends a Basic.Cancel for a consumer
        receiving messages.

        :param pika.frame.Method method_frame: The Basic.Cancel frame

        """
        logger.info('Consumer was cancelled remotely, shutting down: %r',
                    method_frame)
        if self._channel:
            self._channel.close()

    def on_message(self, unused_channel, basic_deliver, properties, body):
        """Invoked by pika when a message is delivered from RabbitMQ. The
        channel is passed for your convenience. The basic_deliver object that
        is passed in carries the exchange, routing key, delivery tag and
        a redelivered flag for the message. The properties passed in is an
        instance of BasicProperties with the message properties and the body
        is the message that was sent.

        :param pika.channel.Channel unused_channel: The channel object
        :param pika.Spec.Basic.Deliver: basic_deliver method
        :param pika.Spec.BasicProperties: properties
        :param str|unicode body: The message body

        """
        logger.info('Received message # %s from %s',
                    basic_deliver.delivery_tag, properties.app_id)


        td = Threaded_bufr2mqtt(basic_deliver.delivery_tag)
        td.setDaemon(True)
        td.start()
        send_queue.put(body)

        ##self._connection.ioloop.stop()
        #while (td.isAlive()):
        #    #self._connection.ioloop.poll(write_only=True)
        #    time.sleep(3)

        ##self._connection.ioloop.start()


    def not_acknowledge_message(self, delivery_tag):
        """Not Acknowledge the message delivery from RabbitMQ by sending a
        Basic.Nack RPC method for the delivery tag.

        :param int delivery_tag: The delivery tag from the Basic.Deliver frame

        """
        logger.info('Not acknowledging message %s', delivery_tag)
        self._channel.basic_nack(delivery_tag)


    def acknowledge_message(self, delivery_tag):
        """Acknowledge the message delivery from RabbitMQ by sending a
        Basic.Ack RPC method for the delivery tag.

        :param int delivery_tag: The delivery tag from the Basic.Deliver frame

        """
        logger.info('Acknowledging message %s', delivery_tag)
        self._channel.basic_ack(delivery_tag)

    def stop_consuming(self):
        """Tell RabbitMQ that you would like to stop consuming by sending the
        Basic.Cancel RPC command.

        """
        if self._channel:
            logger.info('Sending a Basic.Cancel RPC command to RabbitMQ')
            self._channel.basic_cancel(self.on_cancelok, self._consumer_tag)

    def on_cancelok(self, unused_frame):
        """This method is invoked by pika when RabbitMQ acknowledges the
        cancellation of a consumer. At this point we will close the channel.
        This will invoke the on_channel_closed method once the channel has been
        closed, which will in-turn close the connection.

        :param pika.frame.Method unused_frame: The Basic.CancelOk frame

        """
        logger.info('RabbitMQ acknowledged the cancellation of the consumer')
        self.close_channel()

    def close_channel(self):
        """Call to close the channel with RabbitMQ cleanly by issuing the
        Channel.Close RPC command.

        """
        logger.info('Closing the channel')
        self._channel.close()

    def run(self):
        """Run the example consumer by connecting to RabbitMQ and then
        starting the IOLoop to block and allow the SelectConnection to operate.

        """
        self._connection = self.connect()
        self._connection.add_timeout(3, self.mgrack)
        self._connection.ioloop.start()


    def mgrack(self):
        """
        """

        try:
            response=receive_queue.get_nowait()
        except Queue.Empty:
            response=("",0)

        #try:
        #    logger.info('RESPONSE %s %s' % response)
        #except:
        #    logger.info('STRANGE RESPONSE')
        #    print response

        if (response[0] == "ok"):
            logger.info('ACK %s' % response[1])
            self.acknowledge_message(response[1])
        elif (response[0] == "nook"):
            logger.info('NOT ACK %s' % response[1])
            self.not_acknowledge_message(response[1])

        self._connection.add_timeout(3, self.mgrack)

    def stop(self):
        """Cleanly shutdown the connection to RabbitMQ by stopping the consumer
        with RabbitMQ. When RabbitMQ confirms the cancellation, on_cancelok
        will be invoked by pika, which will then closing the channel and
        connection. The IOLoop is started again because this method is invoked
        when CTRL-C is pressed raising a KeyboardInterrupt exception. This
        exception stops the IOLoop which needs to be running for pika to
        communicate with RabbitMQ. All of the commands issued prior to starting
        the IOLoop will be buffered but not processed.

        """
        logger.info('Stopping')
        self._closing = True
        self.stop_consuming()
        self.close_connection()
        #self._connection.ioloop.start()
        logger.info('Stopped')

    def close_connection(self):
        """This method closes the connection to RabbitMQ."""
        logger.info('Closing connection')
        self._connection.close()


def main(amqp2mqttd):

    logger.error("Start version: "+rmap.__version__)

    print ' [*] Waiting for messages. To exit press CTRL+C'

    consumer = amqpConsumer()
    try:
        consumer.run()

    except KeyboardInterrupt:
        consumer.stop()


if __name__ == '__main__':

    import sys, os
    amqp2mqttd.cwd=os.getcwd()

    if amqp2mqttd.service():


        formatter = logging.Formatter('%(asctime) -1s %(levelname)s %(name) -1s %(funcName) -1s %(lineno) -5d: %(message)s')
        handler = logging.handlers.RotatingFileHandler(rmap.settings.logfileamqp2mqttd, maxBytes=5000000, backupCount=10)
        handler.setFormatter(formatter)
        handler.setLevel(logging.DEBUG)
        logger=logging.getLogger(__name__)
        logger.addHandler(handler)

        sys.stdout.write("Daemon started with pid %d\n" % os.getpid())
        sys.stdout.write("Daemon stdout output\n")
        sys.stderr.write("Daemon stderr output\n")

        main(amqp2mqttd)  # (this code was run as script)

        for proc in amqp2mqttd.procs:
            proc.wait()

        sys.exit(0)
