#!/usr/bin/env python

# Copyright (c) 2013 Paolo Patruno <p.patruno@iperbole.bologna.it>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# 3. Neither the name of mosquitto nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'rmap.settings'
import django
django.setup()

from rmap import daemon
from rmap import __version__
from rmap import mqtt2graphite
import rmap.settings

# TODO port those on config file !
MQTT_HOST = 'localhost'
CARBON_SERVER = '127.0.0.1'
CARBON_PORT = 2003


MAPFILE = rmap.settings.mapfilemqtt2graphited
logfilermap=rmap.settings.logfilemqtt2graphited
errfilermap=rmap.settings.errfilemqtt2graphited
lockfilermap=rmap.settings.lockfilemqtt2graphited
userrmap=rmap.settings.usermqtt2graphited
grouprmap=rmap.settings.groupmqtt2graphited


mqtt2graphited = daemon.Daemon(
        stdin="/dev/null",
        stdout=logfilermap,
        stderr=errfilermap,
        pidfile=lockfilermap,
        user=userrmap,
        group=grouprmap
)


def main ():

    m2g=mqtt2graphite.mqtt2graphite(MQTT_HOST, CARBON_SERVER, CARBON_PORT, MAPFILE)
    m2g.run()


if __name__ == '__main__':
    
  import os,sys

  # this is a triky for ubuntu and debian that remove /var/run every boot
  # ATTENTION, this should be a security problem
  path=os.path.dirname(lockfilermap)
  if (not os.path.lexists(path) and path == "/var/run/rmap" ):
    os.mkdir(path)
    if (os.getuid() == 0):
      user=userrmap
      group=grouprmap
      if user is not None and group is not None:
        from pwd import getpwnam
        from grp import getgrnam
        uid = getpwnam<(user)[2]
        gid = getgrnam(group)[2]
        os.chown(path,uid,gid)

  if mqtt2graphited.service(noptions=1000):

    sys.stdout.write("Stationd version "+__version__+"\n")
    sys.stdout.write("Daemon started with pid %d\n" % os.getpid())
    sys.stdout.write("Daemon stdout output\n")
    sys.stderr.write("Daemon stderr output\n")

    sys.exit(main())  # (this code was run as script)

