# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20160216_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[(b'TMP', b'I2C TMP temperature sensor'), (b'ADT', b'I2C ADT temperature sensor'), (b'BMP', b'I2C BMP085/BMP180 pressure sensor'), (b'HIH', b'I2C HIH6100 series humidity sensor'), (b'DW1', b'I2C Davis/Inspeed/Windsonic wind direction and intensity adapter'), (b'TBR', b'I2C Tipping bucket rain gauge adapter'), (b'RF24', b'RF24 Network jsonrpc'), (b'STH', b'I2C TH module, one shot mode'), (b'ITH', b'I2C TH module, report mode, istantaneous values'), (b'NTH', b'I2C TH module, report mode, minimum values'), (b'MTH', b'I2C TH module, report mode, mean values'), (b'XTH', b'I2C TH module, report mode, maximum values')], default=b'TMP', help_text='Type of sensor', max_length=4),
        ),
        migrations.AlterField(
            model_name='transportserial',
            name='baudrate',
            field=models.PositiveIntegerField(choices=[(9600, b'9600'), (19200, b'19200'), (38400, b'38400'), (115200, b'115200')], default=9600, help_text='Baud rate'),
        ),
    ]
