# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_auto_20161221_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcode',
            name='bcode',
            field=models.CharField(default=b'B00000', help_text='Bcode as defined in dballe btable', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='active',
            field=models.BooleanField(default=True, help_text='Activate this sensor to take measurements', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='type',
            field=models.CharField(default=b'TMP', help_text='Type of sensor', max_length=4, unique=True),
        ),
    ]
