# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_auto_20170120_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporttcpip',
            name='name',
            field=models.CharField(choices=[(b'master', b'master board 1'), (b'master2', b'master board 2'), (b'master3', b'master board 3'), (b'master4', b'master board 4'), (b'stima', b'master stima 1'), (b'stima2', b'master stima 2'), (b'stima3', b'master stima 3'), (b'stima4', b'master stima 4')], default=b'master', help_text='Name DSN solved (for master board only)', max_length=50),
        ),
    ]
