# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_auto_20180503_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFirmwareMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, default=b'', help_text='MAC address', max_length=128)),
                ('swversion', models.CharField(blank=True, default=b'', help_text='Software version', max_length=255)),
                ('swlastupdate', models.DateTimeField(blank=True, help_text='Software last update date', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='board',
            name='swlastupdate',
        ),
        migrations.RemoveField(
            model_name='board',
            name='swversion',
        ),
        migrations.AddField(
            model_name='boardfirmwaremetadata',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.Board'),
        ),
    ]
