# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetadata',
            fields=[
                ('name', models.SlugField(help_text='Network name', max_length=80, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Network description', max_length=200)),
                ('provider', models.CharField(blank=True, help_text='Data provider', max_length=200)),
                ('provider_url', models.URLField(blank=True, help_text='Main site of the data provider')),
                ('licenze', models.CharField(blank=True, help_text='Data licenze', max_length=200)),
                ('licenze_url', models.URLField(blank=True, help_text='Data licenze url')),
            ],
        ),
    ]
