# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(default='', help_text='Firmware name', max_length=30, unique=True),
        ),
    ]
