# Generated by Django 2.2.17 on 2022-04-12 16:09

from django.db import migrations, models
import rmap.stations.models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_stima_37'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportmqtt',
            name='mqttpassword',
            field=models.CharField(blank=True, default='', help_text='MQTT password', max_length=50, null=True),
        ),
    ]
