# Generated by Django 2.2.17 on 2022-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20220509_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmetadata',
            name='ident',
            field=models.CharField(blank=True, help_text='identifier for mobile station (should be equal to your username)', max_length=9, null=True),
        ),
    ]
