# Generated by Django 2.2.17 on 2022-05-18 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0005_stationmetadata_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportserial',
            name='baudrate',
            field=models.PositiveIntegerField(choices=[(9600, '9600'), (19200, '19200'), (38400, '38400'), (115200, '115200')], default=115200, help_text='Baud rate'),
        ),
        migrations.AlterUniqueTogether(
            name='stationmetadata',
            unique_together={('ident', 'lat', 'lon', 'network'), ('slug', 'user')},
        ),
    ]
