# Generated by Django 2.2.17 on 2022-05-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20220518_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmetadata',
            name='ident',
            field=models.CharField(blank=True, default='', help_text='identifier for mobile station (should be equal to your username)', max_length=9),
        ),
    ]
