# Generated by Django 2.2.17 on 2023-01-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_auto_20220904_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='driver',
            field=models.CharField(choices=[('CAN', 'Cyphal over CAN-BUS'), ('I2C', 'I2C drivers'), ('RF24', 'RF24 Network jsonrpc'), ('SERI', 'SERIAL drivers over serial port'), ('JRPC', 'INDIRECT jsonrpc over some transport')], default='I2C', help_text='Driver to use', max_length=4),
        ),
    ]
