# Generated by Django 2.2.17 on 2023-02-22 14:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_auto_20230222_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='sn',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Serial number', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Module type stima not defined'), (10, 'Module send report over ethernet'), (11, 'Module send sample over gsm/gprs'), (20, 'Module acquire rain tips'), (21, 'Module acquire temperature and humidity'), (22, 'Module acquire temperature, humidity and rain'), (23, 'Module acquire air particle'), (24, 'Module acquire leaf wetness'), (25, 'Module acquire wind sensor'), (26, 'Module acquire radiation sensor'), (27, 'Module acquire gas (NO2, CO2)'), (28, 'Module acquire power regulator mppt')], default=0, help_text='Stima V4 standard type'),
        ),
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('base', 'Raspberry base'), ('master', 'Stima V3 master eth transport'), ('slave', 'Stima V3 slave'), ('satellite', 'Stima V3 slave radio transport'), ('gsm', 'Stima V3 master GSM/GPRS transport'), ('bluetooth', 'Stima V3 slave Bluetooth transport'), ('masterv4', 'Stima V4 master eth transport'), ('gsmv4', 'Stima V4 master LTS transport'), ('slavev4', 'Stima V4 slave CAN transport')], help_text='General standard category', max_length=50, null=True),
        ),
    ]
