# Generated by Django 2.2.17 on 2023-02-27 10:28

from django.db import migrations, models
from django.core import serializers

import os

class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_auto_20230222_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttcpip',
            name='pppnumber',
            field=models.CharField(blank=True, default='*99#', help_text='number for LTE PPP access', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='sn',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Serial number', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='address',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='I2C address (decimal)', null=True),
        ),
    ]
