# Generated by Django 2.2.17 on 2023-05-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_auto_20230227_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMaintStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastupdate', models.DateTimeField(blank=True, help_text='Last status update date', null=True)),
                ('statusb1', models.BooleanField(help_text='Last status bit 1', null=True)),
                ('statusb2', models.BooleanField(help_text='Last status bit 2', null=True)),
                ('statusb3', models.BooleanField(help_text='Last status bit 3', null=True)),
                ('statusb4', models.BooleanField(help_text='Last status bit 4', null=True)),
                ('statusb5', models.BooleanField(help_text='Last status bit 5', null=True)),
                ('statusb6', models.BooleanField(help_text='Last status bit 6', null=True)),
                ('statusb7', models.BooleanField(help_text='Last status bit 7', null=True)),
                ('statusb8', models.BooleanField(help_text='Last status bit 8', null=True)),
                ('statusb9', models.BooleanField(help_text='Last status bit 9', null=True)),
                ('statusb10', models.BooleanField(help_text='Last status bit 10', null=True)),
                ('statusb11', models.BooleanField(help_text='Last status bit 11', null=True)),
                ('statusb12', models.BooleanField(help_text='Last status bit 12', null=True)),
                ('statusb13', models.BooleanField(help_text='Last status bit 13', null=True)),
                ('statusb14', models.BooleanField(help_text='Last status bit 14', null=True)),
                ('statusb15', models.BooleanField(help_text='Last status bit 15', null=True)),
                ('statusb16', models.BooleanField(help_text='Last status bit 16', null=True)),
                ('statusv1', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 1 (%)', null=True)),
                ('statusv2', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 2 (%)', null=True)),
                ('statusv3', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 3 (%)', null=True)),
                ('statusv4', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 4 (%)', null=True)),
                ('statusv5', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 5 (%)', null=True)),
                ('statusv6', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 6 (%)', null=True)),
                ('statusv7', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 7 (%)', null=True)),
                ('statusv8', models.PositiveIntegerField(blank=True, default=None, help_text='Last status value 8 (%)', null=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.Board')),
            ],
        ),
    ]
