# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_auto_20170417_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcode',
            name='offset',
            field=models.FloatField(default=0.0, help_text='Offset coeficent to convert units'),
        ),
        migrations.AddField(
            model_name='bcode',
            name='scale',
            field=models.FloatField(default=1.0, help_text='Scale coeficent to convert units'),
        ),
        migrations.AddField(
            model_name='bcode',
            name='userunit',
            field=models.CharField(default=b'Undefined', help_text='units of measure', max_length=20),
        ),
        migrations.AlterField(
            model_name='bcode',
            name='unit',
            field=models.CharField(default=b'Undefined', help_text='Units of measure', max_length=20),
        ),
    ]
