# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-04 12:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='driver',
            field=models.CharField(choices=[(b'I2C', b'I2C drivers'), (b'RF24', b'RF24 Network jsonrpc'), (b'SERI', b'SERIAL drivers over serial port'), (b'JRPC', b'INDIRECT jsonrpc over some transport')], default=b'I2C', help_text='Driver to use', max_length=4),
        ),
    ]
