# Generated by Django 2.2.17 on 2021-02-24 19:15

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0027_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttcpip',
            name='gsmapn',
            field=models.CharField(default='ibox.tim.it', help_text='APN for gsm access', max_length=50),
        ),
        migrations.AlterField(
            model_name='transportrf24network',
            name='iv',
            field=models.CharField(blank=True, choices=[('0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15', 'preset 1'), ('0,1,1,3,4,5,6,7,8,9,10,11,12,13,14,15', 'preset 2'), ('0,1,2,1,4,5,6,7,8,9,10,11,12,13,14,15', 'preset 3'), ('0,1,2,3,1,5,6,7,8,9,10,11,12,13,14,15', 'preset 4'), ('0,1,2,3,4,1,6,7,8,9,10,11,12,13,14,15', 'preset 5'), ('0,1,2,3,4,5,1,7,8,9,10,11,12,13,14,15', 'preset 6'), ('0,1,2,3,4,5,6,1,8,9,10,11,12,13,14,15', 'preset 7'), ('0,1,2,3,4,5,6,7,1,9,10,11,12,13,14,15', 'preset 8'), ('0,1,2,3,4,5,6,7,8,1,10,11,12,13,14,15', 'preset 9')], help_text='AES cbc iv', max_length=47, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='transportrf24network',
            name='key',
            field=models.CharField(blank=True, choices=[('0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15', 'preset 1'), ('0,1,1,3,4,5,6,7,8,9,10,11,12,13,14,15', 'preset 2'), ('0,1,2,1,4,5,6,7,8,9,10,11,12,13,14,15', 'preset 3'), ('0,1,2,3,1,5,6,7,8,9,10,11,12,13,14,15', 'preset 4'), ('0,1,2,3,4,1,6,7,8,9,10,11,12,13,14,15', 'preset 5'), ('0,1,2,3,4,5,1,7,8,9,10,11,12,13,14,15', 'preset 6'), ('0,1,2,3,4,5,6,1,8,9,10,11,12,13,14,15', 'preset 7'), ('0,1,2,3,4,5,6,7,1,9,10,11,12,13,14,15', 'preset 8'), ('0,1,2,3,4,5,6,7,8,1,10,11,12,13,14,15', 'preset 9')], help_text='AES key', max_length=47, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
