# Generated by Django 2.2.17 on 2023-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0036_auto_20230710_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmetadata',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknow model'), ('manual', 'Human observer'), ('stimav2', 'Stima version 2'), ('stimav3', 'Stima version 3'), ('stimav4', 'Stima version 4')], default='unknown', help_text='Type of the station', max_length=50),
        ),
    ]
