# Generated by Django 2.2.17 on 2025-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0039_river_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Module type stima not defined'), (10, 'Module send report over ethernet'), (11, 'Module send sample over gsm/gprs'), (20, 'Module acquire rain tips'), (21, 'Module acquire temperature and humidity'), (22, 'Module acquire temperature, humidity and rain'), (23, 'Module acquire air particle'), (24, 'Module acquire leaf wetness'), (25, 'Module acquire wind sensor'), (26, 'Module acquire radiation sensor'), (27, 'Module acquire gas (NO2, CO2)'), (28, 'Module acquire power regulator mppt'), (29, 'Module acquire soil humidity'), (30, 'Module acquire level river')], default=0, help_text='Stima V4 standard type'),
        ),
    ]
