# Generated by Django 2.2.17 on 2026-09-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0043_airquality_mobile_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('base', 'Raspberry base'), ('master', 'Stima V3 master eth transport'), ('slave', 'Stima V3 slave'), ('satellite', 'Stima V3 slave radio transport'), ('gsm', 'Stima V3 master GSM/GPRS transport'), ('bluetooth', 'Stima V3 slave Bluetooth transport'), ('masterv4', 'Stima V4 master eth transport'), ('gsmv4', 'Stima V4 master LTS transport'), ('slavev4', 'Stima V4 slave CAN transport'), ('stimawifiv3', 'Stima V3 Stima WiFI'), ('stimawifiv3espnow', 'Stima V3 Stima WiFI ESP NOW')], help_text='General standard category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Module type stima not defined'), (10, 'Module send report over ethernet'), (11, 'Module send sample over gsm/gprs'), (20, 'Module acquire rain tips'), (21, 'Module acquire temperature and humidity'), (22, 'Module acquire temperature, humidity and rain'), (23, 'Module acquire air particle'), (24, 'Module acquire leaf wetness'), (25, 'Module acquire wind sensor'), (26, 'Module acquire radiation sensor'), (27, 'Module acquire gas (NO2, CO2)'), (28, 'Module acquire power regulator mppt'), (29, 'Module acquire soil humidity'), (30, 'Module acquire level river'), (101, 'Module StimaV3 WiFi'), (102, 'Module StimaV3 WiFi ESP NOW')], default=0, help_text='Stima V4 standard type'),
        ),
        migrations.CreateModel(
            name='TransportEspnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Activate this transport for measurements', verbose_name='Active')),
                ('espnowsampletime', models.PositiveIntegerField(default=300, help_text='interval in seconds for publish')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.Board')),
            ],
            options={
                'verbose_name': 'ESP NOW node',
                'verbose_name_plural': 'ESP NOW nodes',
                'ordering': ['board'],
            },
        ),
    ]
