# Generated by Django 2.2.17 on 2026-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0044_auto_20260917_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportespnow',
            name='espnowtype',
            field=models.PositiveIntegerField(choices=[(1, 'Module type master'), (2, 'Module type satellite')], default=1, help_text='Stimawifi espnow type'),
        ),
    ]
