atmega644p: TARGET = atmega644p
atmega644p: MCU_TARGET = atmega644p
atmega644p: F_CPU = 8000000
atmega644p: BOOT_ADR = 0xF000
atmega644p: BAUD_RATE = 57600

atmega644p: $(PROGRAM)_atmega644p.hex
atmega644p: $(PROGRAM)_atmega644p.lst

atmega644p_isp: TARGET = atmega644p
atmega644p_isp: MCU_TARGET = atmega644p
atmega644p_isp: F_CPU = 8000000
atmega644p_isp: BOOT_ADR = 0xF000
atmega644p_isp: BAUD_RATE = 57600

atmega644p_isp: MCU_AVRDUDE = atmega644p
# 8192 byte boot
atmega644p_isp: HFUSE ?= 0xD8
# Full Swing xtal (16MHz) 16KCK/14CK+65ms
atmega644p_isp: LFUSE ?= 0xFF
# 2.7V brownout
atmega644p_isp: EFUSE ?= 0xFD
atmega644p_isp: UNLOCK ?= 0xFF
atmega644p_isp: LOCK ?= 0xCF

atmega644p_isp: clean
atmega644p_isp: $(PROGRAM)_atmega644p.hex
atmega644p_isp: $(PROGRAM)_atmega644p.lst
atmega644p_isp: fuse flash lock
