atmega1284p: TARGET     = atmega1284p
atmega1284p: MCU_TARGET = atmega1284p
atmega1284p: F_CPU      = 16000000
atmega1284p: BOOT_ADR   = 0x1F000
atmega1284p: BAUD_RATE  = 115200

atmega1284p: $(PROGRAM)_atmega1284p.hex
atmega1284p: $(PROGRAM)_atmega1284p.lst

atmega1284p_isp: TARGET     = atmega1284p
atmega1284p_isp: MCU_TARGET = atmega1284p
atmega1284p_isp: F_CPU      = 16000000
atmega1284p_isp: BOOT_ADR   = 0x1F000
atmega1284p_isp: BAUD_RATE  = 115200

atmega1284p_isp: MCU_AVRDUDE = atmega1284p
# 8192 byte boot
atmega1284p_isp: HFUSE     ?= 0xD0
# Full Swing xtal (16MHz) 16KCK/14CK+65ms
atmega1284p_isp: LFUSE     ?= 0xFF
# 2.7V brownout
atmega1284p_isp: EFUSE     ?= 0xFD
atmega1284p_isp: UNLOCK    ?= 0x3F
atmega1284p_isp: LOCK      ?= 0x0F

atmega1284p_isp: $(PROGRAM)_atmega1284p.hex
atmega1284p_isp: $(PROGRAM)_atmega1284p.lst
atmega1284p_isp: fuse flash lock
