# Generated by Django 2.2.17 on 2023-07-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-date',), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketaction',
            options={'ordering': ('-date',), 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ('-date', 'filename'), 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ticketimage',
            options={'ordering': ('-date',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
