#!/usr/bin/python3.4 -s
# GPL. (C) 2014 Paolo Patruno.

# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2 of the License, or 
# (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details. 
# 
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
# 

import os
import logging,logging.handlers

#os.environ['DJANGO_SETTINGS_MODULE'] = 'rmap.settings'
#import django
#django.setup()

from rmap import daemon
import pika, subprocess
import traceback
import rmap.settings
import threading,queue,time

user=rmap.settings.amqpuser
password=rmap.settings.amqppassword
host="localhost"
user="rmap"

MAXMESSAGEFORSECOND=10  # max number of messages to elaborate in one second
TIMESTEP=15             # execute dbadb import everi TIMESTEP seconds

#add option for topic and dsn
class  mydaemon(daemon.Daemon):

    def optionparser(self):
        op = super(mydaemon, self).optionparser()
        op.add_option("-d", "--datalevel",dest="datalevel", help="sample or report: define the istance to run: select topic, dns,logfile, errorfile and lockfile (default %default)", default=None)
        op.add_option("-s", "--stationtype",dest="stationtype", help="fixed or mobile: define the istance to run: select topic, dns,logfile, errorfile and lockfile (default %default)", default=None)
        #op.add_option("-t", "--topic",dest="topic", help="topic root to subscribe on mqtt broker (default %default)", default="rmap")
        #op.add_option("-d", "--dsn",dest="dsn", help="topic root to subscribe on mqtt broker (default %default)", default=rmap.settings.dsnrmap)
        return op 	  				 



amqp2dballed = mydaemon(
        stdin="/dev/null",
        stdout=rmap.settings.logfileamqp2dballed,
        stderr=rmap.settings.errfileamqp2dballed,
        pidfile=rmap.settings.lockfileamqp2dballed,
        user=rmap.settings.useramqp2dballed,
        group=rmap.settings.groupamqp2dballed
)


send_queue = queue.Queue()
receive_queue = queue.Queue()


class Message(object):
    def __init__(self,body,delivery_tag):
        self.delivery_tag=delivery_tag
        self.body=body



class Threaded_bufr2dballe(threading.Thread):

    #def __init__(self,delivery_tag,dsn):
    def __init__(self,dsn):
        threading.Thread.__init__(self)
        #self.delivery_tag=delivery_tag
        self.dsn=dsn
        
    def run(self):

        timestart=time.time()
        while True:
            # buffer messages for TIMESTEP sec
            now=time.time()
            timetosleep=TIMESTEP-(now-timestart)
            if timetosleep >0:
                logging.debug("sleep for: %s" % timetosleep)
                time.sleep(timetosleep)
            timestart=now
            
            messages=[]
            while not send_queue.empty():
                messages.append(send_queue.get())

            if len(messages) > 0:
                logging.debug("elaborate %s messages" % len(messages))
                totalbody=b""
                for message in messages:
                    totalbody += message.body
            
                try:
                    amqp2dballed.procs = [subprocess.Popen(["dbadb","import","-f","--rejected","/dev/null", "--dsn="+self.dsn], stdin=subprocess.PIPE)]
                    outstdout,outstderr=amqp2dballed.procs[0].communicate(input=totalbody)

                    if (outstdout): logging.debug(outstdout)
                    if (outstderr): logging.error(outstderr)

                    status=amqp2dballed.procs[0].wait()
                    if status != 0:
                        logging.error("There were some errors executing dbadb import error: %s" % status)
                        logging.debug("skip message: ")
                        logging.debug(totalbody)
                        logging.debug("---------------------")

                except Exception as exception:
                    logging.error("There were some errors executing dbadb import")
                    logging.error('Exception occured: ' + str(exception))
                    logging.error(traceback.format_exc())
                    status=100
                    #raise
                    # TODO: enqueue in error
                else:

                    logging.info("Task done: dbadb terminated")
                    # error or not error we skip the messages
                    status=0

                finally:
                    send_queue.task_done()

                if status == 0:
                    for message in messages:
                        receive_queue.put_nowait(("ok",message.delivery_tag))
                else:
                    for message in messages:
                        receive_queue.put_nowait(("nook",message.delivery_tag))

                    
                
class amqpConsumer(object):

    def __init__(self,dsn,queue):
        """Create a new instance of the consumer class, passing in the AMQP
        URL used to connect to RabbitMQ.

        :param str amqp_url: The AMQP url to connect with

        """
        self._connection = None
        self._channel = None
        self._closing = False
        self._consumer_tag = None
        self.dsn=dsn
        self.queue=queue

        #self.td = Threaded_bufr2dballe(basic_deliver.delivery_tag,dsn)
        self.td = Threaded_bufr2dballe(dsn)
        self.td.setDaemon(True)
        self.td.start()

        
    def connect(self):
        """This method connects to RabbitMQ, returning the connection handle.
        When the connection is established, the on_connection_open method
        will be invoked by pika.

        :rtype: pika.SelectConnection

        """
        logging.info('Connecting to %s', host)

        credentials=pika.PlainCredentials(user, password)
        return pika.SelectConnection(pika.ConnectionParameters(host=host,credentials=credentials),
                                     self.on_connection_open,
                                     stop_ioloop_on_close=False)


    def on_connection_open(self, unused_connection):
        """This method is called by pika once the connection to RabbitMQ has
        been established. It passes the handle to the connection object in
        case we need it, but in this case, we'll just mark it unused.

        :type unused_connection: pika.SelectConnection

        """
        logging.info('Connection opened')
        self.add_on_connection_close_callback()
        self.open_channel()

    def add_on_connection_close_callback(self):
        """This method adds an on close callback that will be invoked by pika
        when RabbitMQ closes the connection to the publisher unexpectedly.

        """
        logging.info('Adding connection close callback')
        self._connection.add_on_close_callback(self.on_connection_closed)

    def on_connection_closed(self, connection, reply_code, reply_text):
        """This method is invoked by pika when the connection to RabbitMQ is
        closed unexpectedly. Since it is unexpected, we will reconnect to
        RabbitMQ if it disconnects.

        :param pika.connection.Connection connection: The closed connection obj
        :param int reply_code: The server provided reply_code if given
        :param str reply_text: The server provided reply_text if given

        """
        self._channel = None
        if self._closing:
            self._connection.ioloop.stop()
        else:
            logging.warning('Connection closed, reopening in 5 seconds: (%s) %s',
                           reply_code, reply_text)
            self._connection.add_timeout(5, self.reconnect)

    def reconnect(self):
        """Will be invoked by the IOLoop timer if the connection is
        closed. See the on_connection_closed method.

        """
        # This is the old connection IOLoop instance, stop its ioloop
        self._connection.ioloop.stop()

        if not self._closing:
            self.run()

    def open_channel(self):
        """Open a new channel with RabbitMQ by issuing the Channel.Open RPC
        command. When RabbitMQ responds that the channel is open, the
        on_channel_open callback will be invoked by pika.

        """
        logging.info('Creating a new channel')
        self._connection.channel(on_open_callback=self.on_channel_open)

    def on_channel_open(self, channel):
        """This method is invoked by pika when the channel has been opened.
        The channel object is passed in so we can make use of it.

        Since the channel is now open, we'll declare the exchange to use.

        :param pika.channel.Channel channel: The channel object

        """
        logging.info('Channel opened')
        self._channel = channel
        self.add_on_channel_close_callback()

        self.start_consuming()


    def add_on_channel_close_callback(self):
        """This method tells pika to call the on_channel_closed method if
        RabbitMQ unexpectedly closes the channel.

        """
        logging.info('Adding channel close callback')
        self._channel.add_on_close_callback(self.on_channel_closed)

    def on_channel_closed(self, channel, reply_code, reply_text):
        """Invoked by pika when RabbitMQ unexpectedly closes the channel.
        Channels are usually closed if you attempt to do something that
        violates the protocol, such as re-declare an exchange or queue with
        different parameters. In this case, we'll close the connection
        to shutdown the object.

        :param pika.channel.Channel: The closed channel
        :param int reply_code: The numeric reason the channel was closed
        :param str reply_text: The text reason the channel was closed

        """
        logging.warning('Channel %i was closed: (%s) %s',
                       channel, reply_code, reply_text)
        self._connection.close()


    def start_consuming(self):
        """This method sets up the consumer by first calling
        add_on_cancel_callback so that the object is notified if RabbitMQ
        cancels the consumer. It then issues the Basic.Consume RPC command
        which returns the consumer tag that is used to uniquely identify the
        consumer with RabbitMQ. We keep the value to use it when we want to
        cancel consuming. The on_message method is passed in as a callback pika
        will invoke when a message is fully received.

        """
        logging.info('Issuing consumer related RPC commands')
        self.add_on_cancel_callback()
        self._channel.basic_qos(prefetch_count=MAXMESSAGEFORSECOND*TIMESTEP)
        self._consumer_tag = self._channel.basic_consume(self.on_message,self.queue)

    def add_on_cancel_callback(self):
        """Add a callback that will be invoked if RabbitMQ cancels the consumer
        for some reason. If RabbitMQ does cancel the consumer,
        on_consumer_cancelled will be invoked by pika.

        """
        logging.info('Adding consumer cancellation callback')
        self._channel.add_on_cancel_callback(self.on_consumer_cancelled)

    def on_consumer_cancelled(self, method_frame):
        """Invoked by pika when RabbitMQ sends a Basic.Cancel for a consumer
        receiving messages.

        :param pika.frame.Method method_frame: The Basic.Cancel frame

        """
        logging.info('Consumer was cancelled remotely, shutting down: %r',
                    method_frame)
        if self._channel:
            self._channel.close()

    def on_message(self, unused_channel, basic_deliver, properties, body):
        """Invoked by pika when a message is delivered from RabbitMQ. The
        channel is passed for your convenience. The basic_deliver object that
        is passed in carries the exchange, routing key, delivery tag and
        a redelivered flag for the message. The properties passed in is an
        instance of BasicProperties with the message properties and the body
        is the message that was sent.

        :param pika.channel.Channel unused_channel: The channel object
        :param pika.Spec.Basic.Deliver: basic_deliver method
        :param pika.Spec.BasicProperties: properties
        :param str|unicode body: The message body

        """
        logging.info('Received message # %s from %s',
                    basic_deliver.delivery_tag, properties.app_id)


        #td = Threaded_bufr2dballe(basic_deliver.delivery_tag,dsn)
        #td.setDaemon(True)
        #td.start()
        #send_queue.put(basic_deliver.delivery_tag)
        #send_queue.put(body)
        message=Message(body,basic_deliver.delivery_tag)
        send_queue.put(message)

        ##self._connection.ioloop.stop()
        #while (td.isAlive()):
        #    #self._connection.ioloop.poll(write_only=True)
        #    time.sleep(3)

        ##self._connection.ioloop.start()


    def not_acknowledge_message(self, delivery_tag):
        """Not Acknowledge the message delivery from RabbitMQ by sending a
        Basic.Nack RPC method for the delivery tag.

        :param int delivery_tag: The delivery tag from the Basic.Deliver frame

        """
        logging.info('Not acknowledging message %s', delivery_tag)
        self._channel.basic_nack(delivery_tag)


    def acknowledge_message(self, delivery_tag):
        """Acknowledge the message delivery from RabbitMQ by sending a
        Basic.Ack RPC method for the delivery tag.

        :param int delivery_tag: The delivery tag from the Basic.Deliver frame

        """
        logging.info('Acknowledging message %s', delivery_tag)
        self._channel.basic_ack(delivery_tag)

    def stop_consuming(self):
        """Tell RabbitMQ that you would like to stop consuming by sending the
        Basic.Cancel RPC command.

        """
        if self._channel:
            logging.info('Sending a Basic.Cancel RPC command to RabbitMQ')
            self._channel.basic_cancel(self.on_cancelok, self._consumer_tag)

    def on_cancelok(self, unused_frame):
        """This method is invoked by pika when RabbitMQ acknowledges the
        cancellation of a consumer. At this point we will close the channel.
        This will invoke the on_channel_closed method once the channel has been
        closed, which will in-turn close the connection.

        :param pika.frame.Method unused_frame: The Basic.CancelOk frame

        """
        logging.info('RabbitMQ acknowledged the cancellation of the consumer')
        self.close_channel()

    def close_channel(self):
        """Call to close the channel with RabbitMQ cleanly by issuing the
        Channel.Close RPC command.

        """
        logging.info('Closing the channel')
        self._channel.close()

    def run(self):
        """Run the example consumer by connecting to RabbitMQ and then
        starting the IOLoop to block and allow the SelectConnection to operate.

        """
        self._connection = self.connect()
        self._connection.add_timeout(3, self.mgrack)
        self._connection.ioloop.start()


    def mgrack(self):
        """
        """

        while not receive_queue.empty():
            response=receive_queue.get()

            #try:
            #    logging.info('RESPONSE %s %s' % response)
            #except:
            #    logging.info('STRANGE RESPONSE')
            #    print response

            if (response[0] == "ok"):
                logging.info('ACK %s' % response[1])
                self.acknowledge_message(response[1])
            elif (response[0] == "nook"):
                logging.info('NOT ACK %s' % response[1])
                self.not_acknowledge_message(response[1])

        self._connection.add_timeout(3, self.mgrack)

    def stop(self):
        """Cleanly shutdown the connection to RabbitMQ by stopping the consumer
        with RabbitMQ. When RabbitMQ confirms the cancellation, on_cancelok
        will be invoked by pika, which will then closing the channel and
        connection. The IOLoop is started again because this method is invoked
        when CTRL-C is pressed raising a KeyboardInterrupt exception. This
        exception stops the IOLoop which needs to be running for pika to
        communicate with RabbitMQ. All of the commands issued prior to starting
        the IOLoop will be buffered but not processed.

        """
        logging.info('Stopping')
        self._closing = True
        self.stop_consuming()
        self.close_connection()
        #self._connection.ioloop.start()
        logging.info('Stopped')

    def close_connection(self):
        """This method closes the connection to RabbitMQ."""
        logging.info('Closing connection')
        self._connection.close()



def main(self):

    # configure the logger
    formatter=logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s",datefmt="%Y-%m-%d %H:%M:%S")
    handler = logging.handlers.RotatingFileHandler(self.options.stdout, maxBytes=5000000, backupCount=10)
    handler.setFormatter(formatter)
    
    # Add the log message handler to the root logger
    logging.getLogger().addHandler(handler)
    logging.getLogger().setLevel(logging.INFO)

    logging.info('Starting up amqp2dballed')
    
    dsndict={"sample":{},"report":{}}
    dsndict["sample"]["fixed"]=rmap.settings.dsnsample_fixed
    dsndict["sample"]["mobile"]=rmap.settings.dsnsample_mobile
    dsndict["report"]["fixed"]=rmap.settings.dsnreport_fixed
    dsndict["report"]["mobile"]=rmap.settings.dsnreport_mobile

    if (not self.options.datalevel is None):
        if not (self.options.datalevel in list(dsndict.keys())):
            logging.error('Invalid dsn')
            sys.stdout.write("Invalid dsn\n")
            return False

    if (not self.options.stationtype is None):
        if not (self.options.stationtype in list(dsndict[self.options.datalevel].keys())):
            logging.error('Invalid dsn')
            sys.stdout.write("Invalid dsn\n")
            return False

    if (self.options.stationtype is None != self.options.datalevel is None ):
            logging.error('Invalid: only one of datalevel and stationtype options are missed ')
            sys.stdout.write("Invalid: only one of datalevel and stationtype options are missed\n")
            return False

    if (self.options.stationtype is None and self.options.datalevel is None ):
        queue="dballe"
        dsn=rmap.settings.dsn
    else:        
        queue=self.options.datalevel+"_"+self.options.stationtype
        dsn   = dsndict[self.options.datalevel][self.options.stationtype]

    logging.info('Queue: %s' % queue)
    logging.info('DSN: %s'% dsn)
    logging.error("Start version: "+rmap.__version__)

    print(' [*] Waiting for messages. To exit press CTRL+C')

    consumer = amqpConsumer(dsn=dsn,queue=queue)

    try:
        consumer.run()

    except KeyboardInterrupt:
        consumer.stop()




def callback(ch, method, properties, body):
    logging.info("Received message")


    try:
        amqp2dballed.procs = [subprocess.Popen(["dbadb","import","-f","--dsn="+ch.dsn], stdin=subprocess.PIPE)]
        outstdout,outstderr=amqp2dballed.procs[0].communicate(input=body)

        if (outstdout): logging.debug(outstdout)
        if (outstderr): logging.error(outstderr)
            
        status=amqp2dballed.procs[0].wait()
        if status != 0:
            logging.error("There were some errors executing dbadb import error: %s" % status)
            logging.debug("skip message: ")
            logging.debug(body)
            logging.debug("---------------------")

    except Exception as exception:
        logging.error("There were some errors executing dbadb import")
        logging.error('Exception occured: ' + str(exception))
        logging.error(traceback.format_exc())
        raise

    else:
                          
        logging.info("Done")
        ch.basic_ack(delivery_tag = method.delivery_tag)


    # TODO how we can pass procs to daemon ? 

def oldmain(self):

    # configure the logger
    formatter=logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s",datefmt="%Y-%m-%d %H:%M:%S")
    handler = logging.handlers.RotatingFileHandler(self.options.stdout, maxBytes=5000000, backupCount=10)
    handler.setFormatter(formatter)
    
    # Add the log message handler to the root logger
    logging.getLogger().addHandler(handler)
    logging.getLogger().setLevel(logging.INFO)

    logging.info('Starting up amqp2dballed')
    
    dsndict={"sample":{},"report":{}}
    dsndict["sample"]["fixed"]=rmap.settings.dsnsample_fixed
    dsndict["sample"]["mobile"]=rmap.settings.dsnsample_mobile
    dsndict["report"]["fixed"]=rmap.settings.dsnreport_fixed
    dsndict["report"]["mobile"]=rmap.settings.dsnreport_mobile

    if (not self.options.datalevel is None):
        if not (self.options.datalevel in list(dsndict.keys())):
            logging.error('Invalid dsn')
            sys.stdout.write("Invalid dsn\n")
            return False

    if (not self.options.stationtype is None):
        if not (self.options.stationtype in list(dsndict[self.options.datalevel].keys())):
            logging.error('Invalid dsn')
            sys.stdout.write("Invalid dsn\n")
            return False

    if (self.options.stationtype is None != self.options.datalevel is None ):
            logging.error('Invalid: only one of datalevel and stationtype options are missed ')
            sys.stdout.write("Invalid: only one of datalevel and stationtype options are missed\n")
            return False

    if (self.options.stationtype is None and self.options.datalevel is None ):
        queue="dballe"
        dsn=rmap.settings.dsn
    else:        
        queue=self.options.datalevel+"_"+self.options.stationtype
        dsn   = dsndict[self.options.datalevel][self.options.stationtype]

    logging.info('Queue: %s' % queue)
    logging.info('DSN: %s'% dsn)
    
    credentials=pika.PlainCredentials(user, password)

    connection = pika.BlockingConnection(pika.ConnectionParameters(
        host=host,credentials=credentials))
    channel = connection.channel()

    #save in channel for callback
    channel.dsn=dsn

    #channel.queue_declare(queue=queue)
    
    channel.basic_consume(callback,
            queue=queue,
            no_ack=False)

    try:
        logging.info('Waiting for messages. To exit press CTRL+C')
        channel.start_consuming()

    # log and retry on exception 
    except Exception as exception:
        logging.error('Exception occured: ' + str(exception))
        logging.error(traceback.format_exc())
        logging.error('Start_consuming failed')
        status=False    
    # terminate on keyboard interrupt
    except KeyboardInterrupt:
        sys.stdout.write("keyboard interrupt\n")
        logging.info("keyboard interrupt\n")
        status=True    
    # terminate without error
    else:
        # no exception was raised
        logging.info('Start_consuming terminated')
        status=True
    finally:
        # we have to terminate together with other exceptions                          
        logging.info('Subprocess finished')

    return status

                          

if __name__ == '__main__':

    import sys, os
    amqp2dballed.cwd=os.getcwd()

    if amqp2dballed.service():

        sys.stdout.write("Daemon started with pid %d\n" % os.getpid())
        sys.stdout.write("Daemon stdout output\n")
        sys.stderr.write("Daemon stderr output\n")

        status=main(amqp2dballed)  # (this code was run as script)

        for proc in amqp2dballed.procs:
            proc.wait()

        sys.exit(status)
