# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphite-dballe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriestag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='seriestag',
            name='series',
        ),
        migrations.RemoveField(
            model_name='seriestag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='seriestag',
            name='value',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='SeriesTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagValue',
        ),
    ]
