# Generated by Django 2.2.17 on 2023-07-28 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpc',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'RPC', 'verbose_name_plural': 'RPCSs'},
        ),
        migrations.AlterField(
            model_name='rpc',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
