# Generated by Django 2.2.17 on 2025-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpc',
            name='active',
            field=models.BooleanField(default=True, help_text='Active RPC', verbose_name='Active'),
        ),
    ]
