# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='history',
            field=models.TextField(default=''),
        ),
    ]
