# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeorefencedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
