# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import geoimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georefencedimage',
            name='category',
            field=models.CharField(choices=[('meteo', 'Meteo phenomena'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='georefencedimage',
            name='image',
            field=geoimage.models.DeletingImageField(upload_to=''),
        ),
    ]
