# Generated by Django 2.2.17 on 2023-01-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoimage', '0002_auto_20180822_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='georefencedimage',
            old_name='ident',
            new_name='user',
        ),
    ]
