# Generated by Django 2.2.17 on 2025-02-01 18:46

from django.db import migrations, models
import geoimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoimage', '0003_auto_20230118_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georefencedimage',
            name='comment',
            field=models.TextField(help_text='Image description', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='georefencedimage',
            name='image',
            field=geoimage.models.DeletingImageField(help_text='File with image', upload_to=''),
        ),
    ]
