= Memory Usage checking Library for Arduino =

This is a library for Arduino to see memory usage during a program execution.

For more information about this library please visit us at
http://www.locoduino.org/spip.php?article149 (in french)

In extras folder, click on Doc/index.html to have a complete documentation in English in your browser.

== License ==

Copyright (c) 2015-2021 Locoduino.org. All right reserved.
Copyright (c) 2015-2021 Thierry Paris.  All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA