# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 13:57
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=tagging.fields.TagField(blank=True, default='', max_length=255),
        ),
    ]
